Flexible buffer bindings
napframework/nap pull request #67
Opened 2024-11-02 01:47 UTC by lshoek

Removes restriction that would assert that all buffers bound to bindings would have the same size as specified by the shader declaration. Buffer declarations are also permitted to have an element size of zero. This makes it possible to define buffer bindings without specifying the size in the shader:
```
layout(std430) restrict readonly buffer InPositions
{
	vec4 positions[];
};
```
We only check that the buffer stride equals the stride in the declaration.

Also:
- Solve some validation errors due to insufficient render target clear colors (these must be greater than or equal to the number of attachments)
- Added a texture copy function that wraps `vkCmdCopyImage`

2024-11-18 13:33 UTC, cklosters requested changes
I support the changes, see comments

2024-11-18 13:33 UTC, cklosters commented on system_modules/naprender/src/bufferbindinginstance.cpp
> +		const auto* buffer_object_declaration = rtti_cast<const BufferObjectDeclaration>(&declaration);
This call seems to be redundant now? You can call `declaration.getBufferDeclaration()` directly, removing the need for this static function completely?

2024-11-18 13:33 UTC, cklosters commented on system_modules/naprender/src/rendertarget.cpp
> +		clear_values[2].color = { mClearColor[0], mClearColor[1], mClearColor[2], mClearColor[3] };
Is this the right way to solve this? I understand that the number of clear values must be greater or equal than the number of attachments, but why are there exactly 3 if not more? Can't we properly determine this?

2024-11-18 13:33 UTC, cklosters commented on system_modules/naprender/src/shader.cpp
> +		auto member_type = compiler.get_type(type.member_types[index]);
I understand that sometimes it is better or more convenient to use `auto`, but in this case the type is rather useful and short enough to type out. It's therefore not necessary to rename it to `auto`.

2024-11-18 13:33 UTC, cklosters commented on system_modules/naprender/src/shader.cpp
> +				auto value_type = getShaderVariableValueType(member_type);
Again, no need to hide the type by using `auto` here

2024-11-18 13:33 UTC, cklosters commented on system_modules/naprender/src/textureutils.cpp
> +			auto mipWidth = static_cast<int32>(texWidth);
Don't use camel case here

2024-11-18 13:33 UTC, cklosters commented on system_modules/naprender/src/textureutils.cpp
> +			transitionImageLayout(commandBuffer, srcTexture.getHandle().getImage(),
Why explicitly to read and not restore previous state?

2025-01-06 13:40 UTC, lshoek commented on system_modules/naprender/src/bufferbindinginstance.cpp
> +		const auto* buffer_object_declaration = rtti_cast<const BufferObjectDeclaration>(&declaration);
Yes!

2025-01-06 13:44 UTC, lshoek commented on system_modules/naprender/src/shader.cpp
> +		auto member_type = compiler.get_type(type.member_types[index]);
restored it, it's also conventional in this file

2025-01-06 13:48 UTC, lshoek commented on system_modules/naprender/src/rendertarget.cpp
> +		clear_values[2].color = { mClearColor[0], mClearColor[1], mClearColor[2], mClearColor[3] };
This render target always uses three attachments, so it is safe to assume three clear values. The implementation before violated the Vulkan spec:
https://registry.khronos.org/vulkan/specs/latest/html/vkspec.html#VUID-VkRenderPassBeginInfo-clearValueCount-00902

2025-01-06 13:51 UTC, lshoek commented on system_modules/naprender/src/shader.cpp
> +				auto value_type = getShaderVariableValueType(member_type);
`nap::EShaderVariableValueType` is too wordy and `getShaderVariableValueType` spells out the type

2025-01-06 14:01 UTC, lshoek commented
Made changes to `naprender` such that image layouts are properly tracked. NAP always assumed image layout `SHADER_READ` after any render pass, and would not update `nap::ImageData`. This can no longer fly as we want to perform other operations on textures such as clear/blit/copy without having to guess the image layout.

I ran into some of there problems on a project where I implemented render target content conservation. Now merging this back into NAP, so `nap::RenderTarget` now has the property `Clear` (true by default) that lets you avoid clearing the render target! Very useful in some cases like feedback!

2025-01-06 14:01 UTC, lshoek commented on system_modules/naprender/src/textureutils.cpp
> +			transitionImageLayout(commandBuffer, srcTexture.getHandle().getImage(),
This one required some plumbing, see comment

2025-02-12 15:40 UTC, cklosters reviewed
The scattered usage of `syncLayout();` impacts the interface negatively - only the render target should be allowed to update the image layout after submission, the path to do so shouldn't therefore be public.  I'm going to try and find a better, more occluded method to achieve this. Low level system tracking should never be public.

2025-02-13 17:18 UTC, cklosters commented
Whilst reviewing this PR I ran into a couple of issues that should be tackled before we can merge this, first:

- Fix the vulkan validation errors (see https://github.com/napframework/nap/pull/67#issuecomment-2657219277)
- Remove `syncLayout()` - this should not be public (see https://github.com/napframework/nap/pull/67#pullrequestreview-2612373185)
    - Instead introduce a `getFinalLayout()` on every `IRenderTarget` - which is a property of the target (not texture)
    - The texture should internally update it's layout when the render pass completes
    - This can be done by installing a layoutListener or using signals, hiding the sync interface from the end-user
    - As an added benefit we can remove `Texture::getTargetLayout()`, which is confusing and doesn't reflect intended usage

Boils down to allowing textures to be less confined - they manage their own state internally and / or reflect external changes through a better contract (abstract listener for example).

2025-02-15 12:03 UTC, lshoek commented
Fixed the validation errors. As for the layout syn, I agree the final layout should be stored in the render target and render textures should update their internal image data when a render pass completes. Render textures should not be aware of the render targets they are hooked up to however. Let's discuss how to set this up next week.

2025-02-19 08:12 UTC, merged